### ISSUE TITLE
Plugin Crashing Website

### ISSUE THREAD

**Issue by zachkinsey** [feperrella/Integrate-Elementor-Form-with-Mailster#1]
The plugin crashes the entire website with default theme, elementor, & Mailster plugin activated.

Fatal error: Uncaught Error: Call to undefined function is_plugin_active() in /usr/local/lsws/mysite/html/wp-content/plugins/integrate-elementor-form-with-mailsterq/includes/class-integrate-elementor-form-with-mailster.php:124 Stack trace: #0 /usr/local/lsws/mysite/html/wp-includes/class-wp-hook.php(287): Integrate_Elementor_Form_With_Mailster->init() #1 /usr/local/lsws/mysite/html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters() #2 /usr/local/lsws/mysite/html/wp-includes/plugin.php(478): WP_Hook->do_action() #3 /usr/local/lsws/mysite/html/wp-settings.php(409): do_action() #4 /usr/local/lsws/mysite/html/wp-config.php(80): require_once('/usr/local/lsws...') #5 /usr/local/lsws/mysite/html/wp-load.php(37): require_once('/usr/local/lsws...') #6 /usr/local/lsws/mysite/html/wp-admin/admin.php(34): require_once('/usr/local/lsws...') #7 /usr/local/lsws/mysite/html/wp-admin/plugins.php(10): require_once('/usr/local/lsws...') #8 {main} thrown in /usr/local/lsws/mysite/html/wp-content/plugins/integrate-elementor-form-with-mailsterq/includes/class-integrate-elementor-form-with-mailster.php on line 124

**Comment by feperrella** [comment]
Do you have Elementor Pro installed and activated also?

If you could update the file, for testing purposes:
/integrate-elementor-form-with-mailsterq/includes/class-integrate-elementor-form-with-mailster.php
Line 124, from:
```
if ( ! is_plugin_active( 'elementor-pro/elementor-pro.php' ) ) {
```
to
```
if ( ! in_array( 'elementor-pro/elementor-pro.php', apply_filters( 'active_plugins', get_option( 'active_plugins' ) ) ) ) {
```

To check if it works...

**Comment by zachkinsey** [comment]
Yes, it still goes into a fatal error

**Comment by zachkinsey** [comment]
And, I'll check that really quick

**Comment by zachkinsey** [comment]
Inputting that code fixed the fatal error 👍

**Comment by feperrella** [comment]
Thanks, will submit a fix.
